name: Send CVE Reports to Jira

description: Uploads vulnerability scan reports to Jira

inputs:
  reports:
    description: "Comma-separated list of SARIF report file paths"
    required: true
  jira-url:
    description: "Jira webhook URL"
    required: true
  jira-auth-token:
    description: "Jira authentication token"
    required: true
  minimum-level:
    description: "Minimum severity level to report"
    required: false
    default: "MEDIUM"
  bump-cisa-cves:
    description: |
      Bump the CVE records found from the CISA KEV catalog to at least HIGH priority.
      These CVEs will have their record names prefixed with "[CISA] ", and will not
      be affected by the minimum-level argument.
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Checkout k8s-workflows repository
      uses: actions/checkout@v4
      with:
        repository: "canonical/k8s-workflows"
        path: "k8s-workflows"

    - name: Send vulnerability records
      shell: bash
      run: |
        cisa_catalog=""
        if [[ "${{ inputs.bump-cisa-cves }}" == "true" ]]; then
          # Obtain CISA Known Exploited Vulnerabilities list.
          curl -sSL -o ./cisa_kev_catalog.json \
            https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json
          cisa_catalog="./cisa_kev_catalog.json"
        fi

        IFS=',' read -ra REPORTS <<< "${{ inputs.reports }}"
        for report in "${REPORTS[@]}"; do
          ./k8s-workflows/scripts/cve-reports/send-scan.py --report-path="$report" \
            --jira-url="${{ inputs.jira-url }}" \
            --jira-auth-token="${{ inputs.jira-auth-token }}" \
            --cisa-catalog=$cisa_catalog \
            --add-github-meta --minimum-level="${{ inputs.minimum-level }}" --verbose
        done
